name: 欢迎使用 Message Board
description: 欢迎来到我们的消息板社区！请先阅读以下内容，再提交你的问题或想法。
title: "[Welcome] 欢迎加入"
labels:
  - welcome
assignees:
  - guomengtao
body:
  - type: markdown
    attributes:
      value: |
        ## 👋 欢迎！
        感谢你来到我们的消息板社区。这里你可以：
        - 提出新想法和功能请求
        - 反馈问题或 Bug
        - 与社区成员交流意见

        **使用指南：**
        1. 选择最合适的模板提交你的内容（Idea / Bug / Feature）
        2. 详细描述你的问题或建议
        3. 我们会尽快处理你的 Issue

        希望你能在这里收获愉快的体验！🎉

  - type: textarea
    id: introduction
    attributes:
      label: 请简单介绍一下你自己或你的使用场景
      placeholder: 例如：我是学生，想用这个留言板做课程实验...
    validations:
      required: false
