name: 欢迎使用 Message Board
about: 欢迎来到我们的消息板社区！请先阅读以下内容，再提交你的问题或想法。
title: 欢迎
labels: ["welcome"]
body: |
  ## 👋 欢迎！
  感谢你来到我们的消息板社区。这里你可以：
  - 提出新想法和功能请求
  - 反馈问题或 Bug
  - 与社区成员交流意见

  **使用指南：**
  1. 选择最合适的模板提交你的内容（Idea / Bug / Feature）
  2. 详细描述你的问题或建议
  3. 我们会尽快处理你的 Issue

  希望你能在这里收获愉快的体验！🎉
